### ISSUE TITLE
Atom-mapping from Lowe's Data

### ISSUE THREAD

**Issue by WesleyyC** [connorcoley/rexgen_direct#10]
Hi, I was looking at the original data from Daniel Lowe [here](https://bitbucket.org/dan2097/patent-reaction-extraction/downloads/) but realized the data you folks processed has a full atom-mapping instead of only the mapping for the atoms in the product. I am wondering if you can share the code for such preprocessing. Thanks!

**Comment by connorcoley** [comment]
The "extra" atom map numbers are just unique numbers to make sure it is defined for every atom, but there is no meaning to the numbering. A code snippet like the following would suffice:

```
import rdkit.Chem as Chem 
from itertools import chain

def complete_mapping(rxn_smi):
    r_smi,agent,p_smi = rxn_smi.split('>')
    r = Chem.MolFromSmiles(r_smi)
    p = Chem.MolFromSmiles(p_smi)
    max_map = max(a.GetAtomMapNum() for a in chain(r.GetAtoms(), p.GetAtoms()))
    for a in chain(r.GetAtoms(), p.GetAtoms()):
        if not a.GetAtomMapNum():
            a.SetAtomMapNum(max_map+1)
            max_map += 1
    return '>'.join((Chem.MolToSmiles(r), agent, Chem.MolToSmiles(p)))

complete_mapping('[CH3:1][OH:2].[CH3:3][CH2:4]Cl>>[CH3:1][O:2][CH2:4][CH3:3]')
# returns [CH3:1][OH:2].[CH3:3][CH2:4][Cl:5]>>[CH3:1][O:2][CH2:4][CH3:3]
```

**Comment by WesleyyC** [comment]
Got it, thanks!

**Comment by ahseena96** [comment]
@connorcoley : Any way we could know the source of data, w.r.t. the patent info, for the reactions you used? As in, which year and patent number? We have used the USPTO data for one of our projects - trying to map these reactions to the ones we used (not a simple reaction smiles match, as the atom mappings have changed)

**Comment by connorcoley** [comment]
Unfortunately that information wasn’t carried through the pipeline. Would
it be possible to do that comparison with the atom mapping stripped?

**Comment by ahseena96** [comment]
Maybe - will try that out. Thank you.

**Comment by YH-88** [comment]
> The "extra" atom map numbers are just unique numbers to make sure it is defined for every atom, but there is no meaning to the numbering. A code snippet like the following would suffice:
> 
> ```
> import rdkit.Chem as Chem 
> from itertools import chain
> 
> def complete_mapping(rxn_smi):
>     r_smi,agent,p_smi = rxn_smi.split('>')
>     r = Chem.MolFromSmiles(r_smi)
>     p = Chem.MolFromSmiles(p_smi)
>     max_map = max(a.GetAtomMapNum() for a in chain(r.GetAtoms(), p.GetAtoms()))
>     for a in chain(r.GetAtoms(), p.GetAtoms()):
>         if not a.GetAtomMapNum():
>             a.SetAtomMapNum(max_map+1)
>             max_map += 1
>     return '>'.join((Chem.MolToSmiles(r), agent, Chem.MolToSmiles(p)))
> 
> complete_mapping('[CH3:1][OH:2].[CH3:3][CH2:4]Cl>>[CH3:1][O:2][CH2:4][CH3:3]')
> # returns [CH3:1][OH:2].[CH3:3][CH2:4][Cl:5]>>[CH3:1][O:2][CH2:4][CH3:3]
> ```

Hi，Use the method you mentioned to complete the atom mapping in order to map all the atoms of the product. However, 
when I run, it gets 
raise Exception(smiles)
Exception: [CH2:1]([CH:2]([CH:3]([CH:4]([C:5]([CH2:7][OH:41])=[O:42])[OH:40])[OH:39])[OH:38])[OH:12].[NH:32]([CH:33]([C:35](=[O:36])[OH:37])[CH3:91])[C:90]([CH:89]([NH:88][C:87]([CH2:86][CH2:85][CH:81]([NH:80][C:79]([CH:44]([CH3:43])[NH:45][C:46]([CH:47]([O:48][CH:49]1[CH:50]([O:51][CH:52]2[O:53][CH:54]([CH2
:55][OH:56])[CH:57]([OH:58])[CH:59]([OH:60])[CH:61]2[CH2:62][C:63]([CH3:64])=[O:65])[CH:66]([CH2:67][OH:68])[O:69][CH:70]([OH:71])[CH:72]1[NH:73][C:74]([OH:75])=[O:76])[CH3:77])=[O:78])=[O:99])[C:82]([NH2:83])=[O:84])=[O:98])[CH2:93][CH2:94][CH2:95][CH2:96][NH2:97])=[O:92]

After debugging, the reason is found in the rexgen_direct/core_wln_global/mol_graph code block, the content in the image box.
 Can you tell me what I should do about it？Thank you.
![2](https://user-images.githubusercontent.com/56984869/97515085-34cf7a00-19cb-11eb-852b-6a3f0c8b14fa.png)
